# Lesson 09 demo: Numpy

## 1. Set up

To install numpy:

```text
pip install numpy
```

In [2]:
import numpy as np

In [3]:
print(f"Numpy version: {np.__version__}")

Numpy version: 2.2.6


## 2. Creating arrays

### 2.1. From a list

In [5]:
my_arr = np.array([1, 2, 3, 4, 5])
type(my_arr)

numpy.ndarray

In [6]:
my_arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(my_arr)

[[1 2 3]
 [4 5 6]]


### 2.2. Using built-functions

In [9]:
zero_array = np.zeros((3,4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
constant_array = np.full((3,4), 1.0)
print(constant_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 3. Array attributes

In [12]:
constant_array.shape

(3, 4)

In [13]:
constant_array.dtype

dtype('float64')

In [14]:
constant_array.nbytes

96

## 4. Array functions & operations

### 4.1. Arithmetic operations

In [16]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
c = np.array([1])

In [17]:
print(a + b)

[11 22 33 44]


In [20]:
a_list = [10,20,30,40]
b_list = [1,2,3,4]

In [21]:
print(a_list + b_list)

[10, 20, 30, 40, 1, 2, 3, 4]


### 4.2 Statistical methods

In [22]:
print(np.mean(a))

25.0


In [23]:
print(np.sum(a))

100


### 4.3. Methods on axes

In [4]:
arr_2d = np.array([
    [10,20,30,40],
    [1,2,3,4]

])

print(arr_2d)

[[10 20 30 40]
 [ 1  2  3  4]]


In [5]:
arr_2d.shape

(2, 4)

In [6]:
print(np.mean(arr_2d))

13.75


In [7]:
print(np.mean(arr_2d, axis=0))

[ 5.5 11.  16.5 22. ]


In [8]:
print(np.mean(arr_2d, axis=1))

[25.   2.5]


In [36]:
arr_2d.shape

(2, 2, 4)

### 4.4. Shape manipulation

In [37]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
new_arr = arr.reshape(2,6)
print(new_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Selecting data

### 5.1. Indexing

In [65]:
a = np.array([10, 20, 30, 40, 50])
print(a)

[10 20 30 40 50]


In [66]:
print(a[0])

10


In [67]:
print(a[1])

20


In [68]:
print(a[-10])

IndexError: index -10 is out of bounds for axis 0 with size 5

In [70]:
arr_2d = np.array([
    [10, 20, 30, 40],
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(arr_2d)

[[10 20 30 40]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [71]:
print(arr_2d[0])

[10 20 30 40]


In [72]:
first_row = arr_2d[0]
print(first_row)

[10 20 30 40]


In [73]:
last_ele_first_row = first_row[-1]
print(last_ele_first_row)

40


In [74]:
print(arr_2d[1][2])

3


### 5.2. Slicing

In [75]:
print(arr_2d)

[[10 20 30 40]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [76]:
print(arr_2d[0, :])

[10 20 30 40]


In [77]:
print(arr_2d[:, 0])

[10  1  5]


In [78]:
print(arr_2d[0, 1:4])

[20 30 40]


### 5.3. Filtering

In [79]:
a = np.array([10,20,30,40,50,60,70])
print(a)

[10 20 30 40 50 60 70]


In [81]:
b = 50
print(b < 60)

True


In [82]:
mask = a > 20
print(mask)

[False False  True  True  True  True  True]


In [83]:
print(a[mask])

[30 40 50 60 70]


In [84]:
print(a[a > 20])

[30 40 50 60 70]


## 6. A note about copies vs 'views'

In [85]:
copy_a = a[2:5].copy()
print(copy_a)

[30 40 50]


In [86]:
copy_a[1] = 100
print(copy_a)

[ 30 100  50]


In [88]:
print(a)

[10 20 30 40 50 60 70]


In [89]:
b = a[2:5]

In [90]:
b[1] = 100

In [91]:
print(b)

[ 30 100  50]


In [92]:
print(a)

[ 10  20  30 100  50  60  70]


In [93]:
id(a)

140300009313584

In [94]:
id(b)

140300009313776

## 7. Data types

In [111]:
a = np.array([1.8,2,3])

In [109]:
a.dtype

dtype('float64')

In [98]:
b = a.astype(np.float64)
b.dtype

dtype('float64')

In [100]:
c = a.astype(np.float32)
c.dtype

dtype('float32')

In [101]:
print(b)

[1. 2. 3.]


In [102]:
print(c)

[1. 2. 3.]


In [103]:
print(b.nbytes)

24


In [104]:
print(c.nbytes)

12


In [112]:
print(a.astype(np.int32))

[1 2 3]
